name: Build and deploy Node.js app to Azure Web App - invitaion

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Check dist（ここに入れる）
        run: |
          echo "===== ROOT ====="
          ls -la
          echo "===== DIST ====="
          ls -la dist

      - name: Confirm dist
        run: ls -la dist

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "invitaion"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: dist
